version: '3'

services:
    app:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - .:/code
      command: >
        sh -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

    selenium:
      image: selenium/standalone-chrome
      ports:
      - 4444:4444

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

    celery:
      build: .
      command: celery -A kitelogin worker -l info
      volumes:
        - .:/code
      depends_on:
        - redis

    celery-beat:
        build: .
        command: celery -A kitelogin beat -l info
        volumes:
          - .:/code
        depends_on:
          - redis
