# Generated by Django 3.2.2 on 2021-06-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_my_stocks_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
    ]
