# Generated by Django 3.2.2 on 2021-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210609_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_portfolio',
            field=models.IntegerField(default=0),
        ),
    ]
