# Generated by Django 3.2.2 on 2021-06-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_active_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_portfolio',
            field=models.IntegerField(default=0),
        ),
    ]
